const router = require('express').Router()
const authMiddleware = require('../../middlewares/auth')
const auth = require('./auth')
const user = require('./user')
const restaurant = require('./restaurants')
const category = require('./category')
const items = require('./items')
const tax = require('./tax')
const premisestype = require('./premisestype')
const restaurantuser = require('./restauranrusers')
const role = require('./role')
const restaurantpremises = require('./restaurantpremises')
const upload = require('./fileupload')
router.use('/auth', auth)
router.use('/user', authMiddleware)
router.use('/user', user)
router.use('/restaurants', restaurant)
router.use('/category' , category)
router.use('/items' , items)
router.use('/tax', tax)
router.use('/premisestype', premisestype)
router.use('/restaurantpremises', restaurantpremises)
router.use('/role', role)
router.use('/upload' , upload)
router.use('/restaurantusers', restaurantuser)
module.exports = router